# Generated by Django 5.1.1 on 2025-03-11 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_total_amount_order_total_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_cost_done',
            new_name='total_cost_paid',
        ),
    ]
