# Generated by Django 5.1.1 on 2025-04-25 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_abilityscore_background_characterbuild_race_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('allowed_alignments', models.JSONField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='characterbuild',
            name='mythic_path',
            field=models.CharField(choices=[('Aeon', 'Aeon'), ('Angel', 'Angel'), ('Azata', 'Azata'), ('Demon', 'Demon'), ('Devil', 'Devil'), ('Gold Dragon', 'Gold Dragon'), ('Legend', 'Legend'), ('Lich', 'Lich'), ('Trickster', 'Trickster'), ('Swarm-That-Walks', 'Swarm-That-Walks')], max_length=16),
        ),
        migrations.AlterField(
            model_name='characterbuild',
            name='deity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.deity'),
        ),
    ]
