# Generated by Django 5.1.1 on 2025-04-25 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_deity_alter_characterbuild_mythic_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='deity',
            name='allowed_alignments',
        ),
        migrations.AlterField(
            model_name='characterbuild',
            name='alignment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.alignment'),
        ),
        migrations.AddField(
            model_name='deity',
            name='allowed_alignments',
            field=models.ManyToManyField(related_name='deities', to='users.alignment'),
        ),
    ]
