# Generated by Django 5.1.1 on 2025-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alignment_remove_deity_allowed_alignments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='choose_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
