# Generated by Django 5.1.1 on 2025-04-26 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_race_choose_bonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildClassLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_levels', to='users.characterbuild')),
                ('char_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.classes')),
            ],
        ),
    ]
