# Generated by Django 5.1.1 on 2025-04-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_classes_buildclasslevel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
    ]
