# Generated by Django 5.1.1 on 2025-04-29 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_skill_class_hit_die_class_skill_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbuild',
            name='first_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.class'),
        ),
    ]
