# Generated by Django 5.1.1 on 2025-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_characterbuild_first_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='allowed_alignments',
            field=models.ManyToManyField(default=None, related_name='classes', to='users.alignment'),
        ),
    ]
