# Generated by Django 5.1.1 on 2025-04-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_class_allowed_alignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='ability_link',
            field=models.CharField(choices=[('STR', 'Strength'), ('DEX', 'Dexterity'), ('INT', 'Intelligence'), ('WIS', 'Wisdom'), ('CHA', 'Charisma')], default='Dexterity', max_length=16),
        ),
        migrations.AlterField(
            model_name='class',
            name='allowed_alignments',
            field=models.ManyToManyField(blank=True, default=None, related_name='classes', to='users.alignment'),
        ),
    ]
