# Generated by Django 5.1.1 on 2025-04-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_skill_ability_link_alter_class_allowed_alignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='race_images/'),
        ),
    ]
