# Generated by Django 5.1.1 on 2025-04-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_race_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='deity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deity_images/'),
        ),
    ]
