# Generated by Django 5.1.1 on 2025-05-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_deity_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterbuild',
            old_name='description',
            new_name='backstory',
        ),
        migrations.AlterField(
            model_name='characterbuild',
            name='mythic_path',
            field=models.CharField(blank=True, choices=[('Aeon', 'Aeon'), ('Angel', 'Angel'), ('Azata', 'Azata'), ('Demon', 'Demon'), ('Devil', 'Devil'), ('Gold Dragon', 'Gold Dragon'), ('Legend', 'Legend'), ('Lich', 'Lich'), ('Trickster', 'Trickster'), ('Swarm-That-Walks', 'Swarm-That-Walks')], max_length=16),
        ),
    ]
