# Generated by Django 5.1.1 on 2025-05-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_description_characterbuild_backstory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterbuild',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='character_images/'),
        ),
    ]
